apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-ingress
  namespace: sms
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: sohaildevops.site  # replace with EC2 public IP or DNS host (or remove the host field to allow all hosts)
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sms-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sms-frontend
                port:
                  number: 80
