apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sms
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sohail-24/sms-gitops.git
    targetRevision: main
    path: apps/sms

  destination:
    server: https://kubernetes.default.svc
    namespace: sms

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

