apiVersion: v1
kind: Service
metadata:
  name: sms-frontend
  namespace: sms
  labels:
    app: sms-frontend
spec:
  type: ClusterIP
  selector:
    app: sms-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
