apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-backend
  namespace: sms
  labels:
    app: sms-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sms-backend
  template:
    metadata:
      labels:
        app: sms-backend
    spec:
      containers:
        - name: sms-backend
          image: sohail28/sms-backend:v2
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: DATABASE_HOST
              value: sms-postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: smsdb
            - name: POSTGRES_USER
              value: smsuser
            - name: POSTGRES_PASSWORD
              value: smspassword

          # âœ… FIXED PROBES (Django has no /healthz by default)
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20

