apiVersion: v1
kind: Service
metadata:
  name: sms-backend
  namespace: sms
  labels:
    app: sms-backend
spec:
  type: ClusterIP
  selector:
    app: sms-backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
