apiVersion: v1
kind: Service
metadata:
  name: sms-postgres
  namespace: sms
  labels:
    app: sms-postgres
spec:
  type: ClusterIP
  selector:
    app: sms-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
